[workspace]
resolver = "3"
members = [
    "packages/frontend",
    "packages/hydrophobicity",
    "packages/macpepdb",
    "packages/web-common",
    "packages/metrics-peek",
    "packages/uniprot_reader",
    "packages/tui",
]

[workspace.dependencies]
async-compression = "0.4.42"
async-std = "1.13.2"
async-stream = "0.3.6"
axum = "0.8.9"
base64 = "0.22.1"
bytemuck = "1.25"
bytes = "1.9"
chrono = "0.4"
clap = "~4.6.0"
console-subscriber = "0.5.0"
crossbeam = "~0.8.4"
crossterm = "0.28"
csv = "1.4.0"
dashmap = "6.1"
deadpool-postgres = "~0.14.1"
dihardts_omicstools = "~3.1.0"
dioxus = "0.7.1"
dioxus-logger = "0.6.2"
fallible-iterator = "~0.3.0"
flate2 = "1"
futures = "~0.3.32"
futures-util = "0.3.32"
glob = "0.3.3"
gloo-timers = { version = "0.3", features = ["futures"] }
http = "1.4.0"
itertools = "~0.14.0"
js-sys = "0.3"
memchr = "2.8.0"
metrics = "0.24"
metrics-exporter-prometheus = {version = "0.18.1", default-features = false}
metrics-util = "0.20"
mimalloc = "0.1.50"
num-traits = "~0.2.19"
parking_lot = "0.12"
pastey = "~0.2.1"
plotly = "0.14"
postcard = "~1.1.3"
postgres-types = "~0.2.8"
rand = "0.9"
ratatui = "0.29"
reqwest = "0.13.3"
serde = "~1.0.228"
serde_json = "~1.0.149"
static_assertions = "1.1.0"
sysinfo = "0.39.2"
tcmalloc2 = "0.3.2"
tempfile = "3.14"
thiserror = "~2.0.18"
tikv-jemallocator = "0.6"
tinyvec = { version = "1.11", features = ["alloc"] }
tokio = "1.51"
tokio-postgres = "~0.7.12"
toml = "0.8.8"
tower-http = "0.6.8"
tracing = "0.1"
tracing-appender = "0.2"
tracing-loki = "0.2"
tracing-subscriber = "0.3"
url = "2.5"
urlencoding = "2.1.3"
uuid = "1.23.1"
wasm-bindgen = "0.2"
web-sys = "0.3.77"
xxhash-rust = "0.8.15"
zerocopy = "0.8.48"
zstd = "0.13.2"

# workspace
macpepdb = { path = "packages/macpepdb", version = "0.1.0" }
macpepdb-frontend = { path = "packages/frontend" }
macpepdb_web_common = { path = "packages/web-common", version = "0.1.0" }
metrics-peek = { path = "packages/metrics-peek", version = "0.1.0" }
macpepdb_tui = { path = "packages/tui", version = "0.1.0" }
peptide_hydrophobicity = { path = "packages/hydrophobicity", version = "0.1.0" }
uniprot_reader = { path = "packages/uniprot_reader", version = "0.1.0" }
