[package]
name = "macpepdb-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "build.rs"

[dependencies]
anyhow = "1.0.75"
dioxus = { version = "0.6.3", features = ["router", "logger"] }
dioxus-logger = "0.6.2"
futures-util = "0.3.31"
log = "0.4.20"
reqwest = { version = "0.11.22", features = ["json"] }
serde = "1.0.193"
serde_json = "1.0.138"
toml = "0.8.8"

[dev-dependencies]
toml = "0.8.8"

[features]
default = ["web"]
web = ["dioxus/web"]
# desktop = ["dioxus/desktop"]
# mobile = ["dioxus/mobile"]


[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"


