server {
	listen 80;

    root /var/www/html;

    access_log /dev/stdout;
    error_log /dev/stdout;

	location / {
        add_header 'Access-Control-Allow-Origin' '*';
        try_files $uri $uri/ /index.html;
	}
}