use bitvec::{BitArr, field::BitField, order::Lsb0, slice::BitSlice};
use deku::prelude::*;
use pastey::paste;
use thiserror::Error;

use crate::mass_to_int;

const BIT_CODE_LEN: usize = 5;

#[derive(Debug, Error)]
pub enum Error {
    #[error("Invalid amino acid code: {0}")]
    InvalidAminoAcidCode(char),
    #[error("Invalid amino acid bit code: {0:b}")]
    InvalidAminoAcidBitCode(u8),
}

pub type BitCode = BitArr!(for BIT_CODE_LEN, in u8, Lsb0);

pub struct AminoAcid {
    code: char,
    mono_mass: i64,
    bit_code: &'static BitCode,
    aa_bit_code: AminoAcidBitCode,
}

impl AminoAcid {
    pub const BIT_CODE_LEN: usize = BIT_CODE_LEN;

    pub fn code(&self) -> char {
        self.code
    }

    pub fn mono_mass(&self) -> i64 {
        self.mono_mass
    }

    pub fn bit_code(&self) -> &BitSlice<u8, Lsb0> {
        &self.bit_code[..Self::BIT_CODE_LEN]
    }

    pub fn aa_bit_code(&self) -> &AminoAcidBitCode {
        &self.aa_bit_code
    }
}

macro_rules! create_const_amino_acids {
    ([$(($name:literal; $one_letter_code:literal; $mass:literal; $bit_code:literal)),* $(,)?]) => {
        paste! {

            #[derive(Clone, Debug, Eq, Hash, PartialEq, DekuRead, DekuWrite)]
            #[deku(id_type = "u8", bits = "5")]
            pub enum AminoAcidBitCode {
                $(
                    #[deku(id = $bit_code)]
                    [< $one_letter_code:upper>],
                )+
            }

             $(
                const [< $name:replace(" ", "_"):snake:upper _BIT_CODE_RAW>]: u8 = $bit_code;


                const [< $name:replace(" ", "_"):snake:upper _BIT_CODE>]: BitCode = {
                    // make the concrete BitArray type explicit
                    type This = ::bitvec::array::BitArray<[u8; ::bitvec::mem::elts::<u8>(BIT_CODE_LEN)], Lsb0>;
                    // one-element data array initialized from the raw byte
                    This { data: [ [< $name:replace(" ", "_"):snake:upper _BIT_CODE_RAW>] ], ..This::ZERO }
                };

                pub const [< $name:replace(" ", "_"):snake:upper >]: AminoAcid = AminoAcid {
                    code: $one_letter_code,
                    mono_mass: mass_to_int!{$mass},
                    bit_code: &[< $name:replace(" ", "_"):snake:upper _BIT_CODE>],
                    aa_bit_code: AminoAcidBitCode::[< $one_letter_code:upper>],
                };
             )+

             const ALL: &[&'static AminoAcid] = &[
                 $(
                     &[< $name:replace(" ", "_"):snake:upper >],
                 )+
             ];


             impl AminoAcid {
                 /// Returns a canonical or non-canoncial amino acid by one letter code
                 ///
                 /// # Arguments
                 /// * `code` - One letter code
                 ///
                 pub fn by_code(code: char) -> Result<&'static AminoAcid, Error> {
                     match code.to_ascii_uppercase() {
                         $(
                             $one_letter_code => Ok(&[< $name:replace(" ", "_"):snake:upper >]),
                         )+
                         _ => Err(Error::InvalidAminoAcidCode(code)),
                     }
                 }

                 /// Returns a canonical or non-canoncial amino acid by MaCPepDB's 5 bit code
                 ///
                 /// # Arguments
                 /// * `bit_code` - 5 bit code
                 ///
                 pub fn by_bit_code(code: &BitSlice<u8>) -> Result<&'static AminoAcid, Error> {
                     let code_raw = code.load_le::<u8>();
                     match code_raw {
                         $(
                             [< $name:replace(" ", "_"):snake:upper _BIT_CODE_RAW>] => Ok(&[< $name:replace(" ", "_"):snake:upper >]),
                         )+
                         _ => Err(Error::InvalidAminoAcidBitCode(code_raw)),
                     }
                 }

                 /// Returns a canonical or non-canoncial amino acid by MaCPepDB's 5 bit code
                 ///
                 /// # Arguments
                 /// * `bit_code` - 5 bit code
                 ///
                 pub fn by_aa_bit_code(code: &AminoAcidBitCode) -> Result<&'static AminoAcid, Error> {
                     match code {
                         $(
                             AminoAcidBitCode::[< $one_letter_code:snake:upper >] => Ok(&[< $name:replace(" ", "_"):snake:upper >]),
                         )+
                     }
                 }

                 pub fn all() -> &'static [&'static AminoAcid] {
                     ALL
                 }
             }
        }
    };
}

// This file is generated by build.rs
// Do not edit manually!
// It builds the internal amino acids with integer mass
// and the get_internal_amino_acid_by_one_letter_code function
include!(concat!(env!("OUT_DIR"), "/amino_acid.rs"));
