global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "macpepdb"
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ["host.docker.internal:9494"]