name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Start containers
        run: docker-compose up -d --build
      - name: Toolchain fix
        run: rustup toolchain install stable
      - name: Build
        run: cargo build -r --verbose
      - name: Run tests
        run: cargo test -r --verbose
      - name: Stop containers
        if: always()
        run: docker-compose down
